<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>LoadBoost</AssemblyName>
    <RootNamespace>LoadBoost</RootNamespace>
    <KspManaged>E:\ksp\Kerbal Space Program\KSP_x64_Data\Managed</KspManaged>
    <KspGameData>E:\ksp\Kerbal Space Program\GameData</KspGameData>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LoadBoost.Core\LoadBoost.Core.csproj" />
    <Reference Include="Assembly-CSharp">
      <HintPath>$(KspManaged)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(KspManaged)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(KspManaged)\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(KspGameData)\000_Harmony\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
